# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVicNN7mo1aW-19_Nf3tOQoYhkDZjS8p
"""

import pandas as pd
df = pd.read_csv("WHO COVID-19 cases.csv")
afghanistan_data = df[df["Country"] == "Afghanistan"]
print(afghanistan_data)